package com.xmoker.logro.entity;

public enum TipoLogro {
    DIAS_SIN_FUMAR,
    CHECKIN_SEGUIDO,
    COMPLETAR_PERFIL,
    PARTICIPAR_FORO,
    COMPARTIR_PROGRESO,
    NIVEL_MOTIVACION,
    RECUPERAR_SALUD,
    RECAIDAS_EVITADAS,
    DINERO_AHORRADO,
    VIDA_RECUPERADA,
    CO2_EVITADO,
    CAPACIDAD_PULMONAR,
    RIESGO_CV,
    COMPLETAR_RETO_ANSIEDAD

}

