server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xmokerdb
    username: xmoker
    password: xmoker123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG